export const rules = {
  ACTIVITY_SWAPPING_TIME : 5000,
  FOO_MINING_TIME : 1000,
  BAR_MINING_TIME : 3000,
  FOOBAR_CRAFTING_TIME : 3000,
  FOOBAR_CRAFTING_PRICE_FOO : 1,
  FOOBAR_CRAFTING_PRICE_BAR : 1,
  FOOBAR_CRAFTING_CHANCE : 0.6,
  ROBOT_PRICE : 1,
  NB_ROBOTS_START: 2,
}
  
