export const rules = {
  ACTIVITY_SWAPPING_TIME : 5000,
  FOO_MINING_TIME : 1000,
  BAR_MINING_MIN_TIME : 600,
  BAR_MINING_MAX_TIME : 2000,
  FOOBAR_CRAFTING_TIME : 3000,
  FOOBAR_CRAFTING_PRICE_FOO : 1,
  FOOBAR_CRAFTING_PRICE_BAR : 1,
  FOOBAR_CRAFTING_CHANCE : 0.6,
  ROBOT_PRICE : 6,
  NB_ROBOTS_START: 2,
  NB_FOO_START: 0,
  NB_BAR_START: 0,
  VICTORY: 20
}
  
